### ISSUE TITLE
error on make start

### ISSUE THREAD

**Issue by szentigrad3** [LewdHuTao/MusicBot#3]
![Screenshot_20240911_172118](https://github.com/user-attachments/assets/dc4a4ac6-833a-44b7-ad3e-8435531b081d)

**Comment by LewdHuTao** [comment]
fix your docker. check if your docker is running

**Comment by szentigrad3** [comment]
> fix your docker. check if your docker is running

docker is running

**Comment by LewdHuTao** [comment]
> > fix your docker. check if your docker is running
> 
> docker is running

i do some search and found this https://wpsandbox.net/devops/fix-dockerexception-error-while-fetching-server-api-version-httpconnection-request-got-an-unexpected-keyword-argument-chunked-p1016

**Comment by szentigrad3** [comment]
> > > fix your docker. check if your docker is running
> > 
> > 
> > docker is running
> 
> https://wpsandbox.net/devops/fix-dockerexception-error-while-fetching-server-api-version-httpconnection-request-got-an-unexpected-keyword-argument-chunked-p1016
> 
> ^^ i do some search and found that article. it might be an issue with your docker-compose

e.g. docker compose and not like you used to docker-compose (dash separated).

New Command

docker compose ....

**Comment by szentigrad3** [comment]
![Screenshot_20240911_181126](https://github.com/user-attachments/assets/ac62bf68-78cb-429f-b6aa-cc5093577b5a)

**Comment by LewdHuTao** [comment]
> ![Screenshot_20240911_181126](https://private-user-images.githubusercontent.com/5462780/366358724-ac62bf68-78cb-429f-b6aa-cc5093577b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDMyMzcsIm5iZiI6MTcyNjA0MjkzNywicGF0aCI6Ii81NDYyNzgwLzM2NjM1ODcyNC1hYzYyYmY2OC03OGNiLTQyOWYtYjZhYS1jYzUwOTM1NzdiNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMDgyMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUyMzQwODU1ZjgzZmI4NTFkNDE0Njk2YWU4YTliOWY1NmEzZjJlNjc0MTM4MWZiN2ZhYmQxZjk0NWEyMmMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wLyu12s2nkAWXxbEuFnNrVaj3cDKE5bFRk25mWKizcM)



> ![Screenshot_20240911_181126](https://private-user-images.githubusercontent.com/5462780/366358724-ac62bf68-78cb-429f-b6aa-cc5093577b5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDMyMzcsIm5iZiI6MTcyNjA0MjkzNywicGF0aCI6Ii81NDYyNzgwLzM2NjM1ODcyNC1hYzYyYmY2OC03OGNiLTQyOWYtYjZhYS1jYzUwOTM1NzdiNWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMDgyMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUyMzQwODU1ZjgzZmI4NTFkNDE0Njk2YWU4YTliOWY1NmEzZjJlNjc0MTM4MWZiN2ZhYmQxZjk0NWEyMmMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wLyu12s2nkAWXxbEuFnNrVaj3cDKE5bFRk25mWKizcM)

run `make stop` and run `make start` again. this usually happened because lavalink take long time to boot up

**Comment by LewdHuTao** [comment]
did you make any changes on application.yml? like changing the lavalink password
?

**Comment by szentigrad3** [comment]
> did you make any changes on application.yml? like changing the lavalink password ?

no changes

**Comment by LewdHuTao** [comment]
hm thats weird. mine just work fine. can you run the bot without docker using `make start-noll` and host the lavalink seperately. I will try to fix docker-compose settings later 

![image](https://github.com/user-attachments/assets/ed554d85-6178-445b-b945-a6213998c378)

**Comment by LewdHuTao** [comment]
Oh anyway here are my docker and docker-compose version

![image](https://github.com/user-attachments/assets/14fcc561-c6a7-4ca4-b171-6d12a3c36c89)

**Comment by szentigrad3** [comment]
> Oh anyway here are my docker and docker-compose version
> 
> ![image](https://private-user-images.githubusercontent.com/90232327/366372396-14fcc561-c6a7-4ca4-b171-6d12a3c36c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTUzNDYsIm5iZiI6MTcyNjA1NTA0NiwicGF0aCI6Ii85MDIzMjMyNy8zNjYzNzIzOTYtMTRmY2M1NjEtYzZhNy00Y2E0LWIxNzEtNmQxMmEzYzM2Yzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDExNDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZWNiYjg5MjdiNjlhMmI2MTU4MWNhMTZlOWQyNGY4OTM5MGVlZGZmYjYwYjNjOTU5NWFjMjc4YTQzMDlmZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xfKLcFG5GHImffx9tE8zotqNQTszTUzjQPmHWJveO1k)

![Screenshot_20240911_214519](https://github.com/user-attachments/assets/82eb9416-b565-4704-9ea6-ded1eae9a7a9)

**Comment by LewdHuTao** [comment]
can you try change the settings on docker-compose? 

```
healthcheck:
      test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version || exit 1'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 120s # Delay before starting checks
   ```
   
   change `retries: 5` and `start_period: 10s`

**Comment by szentigrad3** [comment]
> can you try change the settings on `docker-compose.yml`?
> 
> ```
> healthcheck:
>       test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version || exit 1'
>       interval: 10s
>       timeout: 10s
>       retries: 3
>       start_period: 120s # Delay before starting checks
> ```
> 
> change `retries: 5` and `start_period: 10s` and after that you run `make stop` and `make start`

yaml: line 15: did not find expected key

**Comment by LewdHuTao** [comment]
uhh nvm just copy this and paste it to your docker-compose.yml

```
services:
  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink
    restart: on-failure
    hostname: docker.lavalink
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins:/opt/Lavalink/plugins
    healthcheck:
      test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version || exit 1'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s # Delay before starting checks
    ports:
      - "2333:2333" # Expose port for other containers or external access if needed

  musicbot:
    container_name: musicbot
    build:
      context: .
      target: musicbot
    ports:
      - "3000:3000" # Not required
    volumes:
      - ./src:/app/src # Mount code directory
    environment:
      - NODE_ENV=production # Set your environment variables if needed
    restart: unless-stopped
    depends_on:
      lavalink:
        condition: service_healthy
```
